name: gitsense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.0
  google_fonts: ^4.0.4
  gql: ^1.0.1-alpha+1730759315362
  graphql: ^5.2.0-beta.11
  graphql_flutter: ^5.1.2
  logger: ^2.5.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  graphql_codegen: ^1.2.1
  build_runner: ^2.4.15
  lints: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - ".env"